In [ ]:
import pandas as pd

In [ ]:
df_artists = pd.read_csv("new_artists_enriched.csv")
df_albuns = pd.read_csv("new_albums_enriched.csv")
df_tracks = pd.read_csv("new_tracks_enriched.csv")

In [ ]:
df_artists.head(10)

,artist_mbid,artist_name,artist_id_spotify,artist_url,followers,popularity,genres,artist_uri
0,NaN,Adele,3XPI2Rik4spEoO1VW3fHk7,https://open.spotify.com/artist/3XPI2Rik4spEoO...,1488,16,['sexy drill'],spotify:artist:3XPI2Rik4spEoO1VW3fHk7
1,875203e1-8e58-4b86-8dcb-7190faf411c5,J. Cole,6l3HvQ5sa6mXTsMTB19rO5,https://open.spotify.com/artist/6l3HvQ5sa6mXTs...,28840542,87,['rap'],spotify:artist:6l3HvQ5sa6mXTsMTB19rO5
2,NaN,Drake,3TVXtAsR1Inumwj472S9r4,https://open.spotify.com/artist/3TVXtAsR1Inumw...,115450362,100,['rap'],spotify:artist:3TVXtAsR1Inumwj472S9r4
3,29e686ca-134e-46d5-8a5b-7193f618ff35,Sonder,4XIn6DuTy0ZSfABDGVzh25,https://open.spotify.com/artist/4XIn6DuTy0ZSfA...,205,21,[],spotify:artist:4XIn6DuTy0ZSfABDGVzh25
4,b7539c32-53e7-4908-bda3-81449c367da6,Lana Del Rey,00FQb4jTyendYWaN8pK0wa,https://open.spotify.com/artist/00FQb4jTyendYW...,59822313,91,[],spotify:artist:00FQb4jTyendYWaN8pK0wa
5,NaN,Pitbull,0TnOYISbd1XYRBk9myaseg,https://open.spotify.com/artist/0TnOYISbd1XYRB...,13267096,89,[],spotify:artist:0TnOYISbd1XYRBk9myaseg
6,c8b03190-306c-4120-bb0b-6f2ebfc06ea9,The Weeknd,1Xyo4u8uXC1ZmMpatF05PJ,https://open.spotify.com/artist/1Xyo4u8uXC1ZmM...,126420080,96,[],spotify:artist:1Xyo4u8uXC1ZmMpatF05PJ
7,285e1285-aecc-478f-a8da-0c8cf69e1217,Miguel,360IAlyVv4PCEVjgyMZrxK,https://open.spotify.com/artist/360IAlyVv4PCEV...,6952247,83,['r&b'],spotify:artist:360IAlyVv4PCEVjgyMZrxK
8,b95ce3ff-3d05-4e87-9e01-c97b66af13d4,Eminem,7dGJo4pcD2V6oG8kP0tJRR,https://open.spotify.com/artist/7dGJo4pcD2V6oG...,111683015,91,"['rap', 'hip hop']",spotify:artist:7dGJo4pcD2V6oG8kP0tJRR
9,e0140a67-e4d1-4f13-8a01-364355bee46e,Justin Bieber,1uNFoZAHBGtllmzznpCI3s,https://open.spotify.com/artist/1uNFoZAHBGtllm...,95114896,96,[],spotify:artist:1uNFoZAHBGtllmzznpCI3s

In [ ]:
df_albuns.head(10)

,album_mbid,album_name,artist_name,album_id,album_type,total_tracks,release_date,release_date_precision,album_url
0,29f224ac-498d-4dcb-9a07-22b1293288ae,21,Adele,0Lg1uZvI312TPqxNWShFXL,album,11,2011-01-24,day,https://open.spotify.com/album/0Lg1uZvI312TPqx...
1,32ef7c3f-96bb-44a3-aa4d-7aa8c9640cf9,2014 Forest Hills Drive,J. Cole,0UMMIkurRUmkruZ3KGBLtG,album,13,2014-12-09,day,https://open.spotify.com/album/0UMMIkurRUmkruZ...
2,NaN,Take Care (Deluxe),Drake,6X1x82kppWZmDzlXXK3y3q,album,19,2011-11-15,day,https://open.spotify.com/album/6X1x82kppWZmDzl...
3,16a0fd7d-307d-4721-9c2b-ddb0d1d847d8,What You Heard,Sonder,10WCcQKzXZot04kzENu62Z,single,1,2019-02-22,day,https://open.spotify.com/album/10WCcQKzXZot04k...
4,NaN,Snow On Tha Bluff,J. Cole,0MXpE6m0mEK0r3TuERb9Yd,single,1,2020-06-16,day,https://open.spotify.com/album/0MXpE6m0mEK0r3T...
5,620e4932-cae3-49d0-9d87-a2685bd4c9c0,4 Your Eyez Only,J. Cole,3CCnGldVQ90c26aFATC1PW,album,10,2016-12-09,day,https://open.spotify.com/album/3CCnGldVQ90c26a...
6,4e102cda-b8f6-4242-b4ae-ce2d16a5eac7,Say Yes to Heaven,Lana Del Rey,6jVg0POvGYH1Pt6lISl3ok,single,2,2023-05-19,day,https://open.spotify.com/album/6jVg0POvGYH1Pt6...
7,NaN,Born to Die - The Paradise Edition,Lana Del Rey,5VoeRuTrGhTbKelUfwymwu,album,23,2012-01-01,day,https://open.spotify.com/album/5VoeRuTrGhTbKel...
8,NaN,Ultraviolence (Deluxe),Lana Del Rey,1ORxRsK3MrSLvh7VQTF01F,album,14,2014-01-01,day,https://open.spotify.com/album/1ORxRsK3MrSLvh7...
9,0c6272c4-f50a-4f80-a302-497038a7f5a0,Young and Beautiful,Lana Del Rey,1D92WOHWUI2AGQCCdplcXL,single,1,2013-01-01,day,https://open.spotify.com/album/1D92WOHWUI2AGQC...

In [ ]:
df_tracks.head(10)

,track_mbid,track_name,artist_name,track_id,isrc,has_feat,artist_count,featured_artists,release_date,duration_ms,...,reccobeats_danceability,reccobeats_energy,reccobeats_instrumentalness,reccobeats_key,reccobeats_liveness,reccobeats_loudness,reccobeats_mode,reccobeats_speechiness,reccobeats_tempo,reccobeats_valence
0,0309071e-e8b6-4263-a68d-c4e4f8c4a988,Lovesong,Adele,7nm6DlSzzJTH1rk2e6EgJz,GBBKS1000352,False,0,[],2011-01-24,316240,...,0.689,0.369,0.002360,0.0,0.1110,-9.407,0.0,0.0278,116.885,0.361
1,f7f85d65-bd9d-4821-9d86-cc0d669bda6c,Apparently,J. Cole,5O59s7bCgTFsXDXlWecyQ1,USQX91402600,False,0,[],2014-12-09,292865,...,0.802,0.544,0.000000,5.0,0.1020,-9.212,1.0,0.0686,133.992,0.570
2,NaN,Cameras / Good Ones Go Interlude - Medley,Drake,2FbGlEPAjNhWvrVvlentVq,USCM51100580,False,0,[],2011-11-15,434960,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,50acbb51-2ddb-451b-8e6e-acbe1dc9799a,What You Heard,Sonder,3a3dQOO19moXPeTt2PomoT,US23A1501167,False,0,[],2019-02-22,238242,...,0.429,0.371,0.000006,2.0,0.1040,-9.017,0.0,0.0327,137.134,0.135
4,ebb59e72-1549-438d-88e9-c27b697f9e90,Snow On Tha Bluff,J. Cole,1oOEkBNp4zWnkD7nWjJdog,QMJMT2003024,False,0,[],2020-06-16,235480,...,0.586,0.512,0.000200,8.0,0.1190,-8.819,0.0,0.0668,75.857,0.235
5,64f84b86-2059-4a01-aab0-c7cd8e9aa341,4 Your Eyez Only,J. Cole,1vvnYpYEMVB4aq9I6tHIEB,QMJMT1601094,False,0,[],2016-12-09,530253,...,0.701,0.485,0.000063,11.0,0.0852,-10.305,0.0,0.3640,78.863,0.496
6,47d724dd-ef88-4337-951e-a42647c21780,She's Mine Pt. 2,J. Cole,0HtOJj7Kl74s1Ngf3MWeif,QMJMT1601084,False,0,[],2016-12-09,209080,...,0.486,0.194,0.006240,2.0,0.1140,-15.265,1.0,0.0712,70.031,0.048
7,346c038a-1bd5-43f6-9bb5-b6e805e219b2,Foldin Clothes,J. Cole,77IAeEz8LEchPN8UNjaTJ2,QMJMT1601090,False,0,[],2016-12-09,316920,...,0.698,0.487,0.000860,7.0,0.0724,-9.887,0.0,0.3120,161.943,0.614
8,303a8f69-1196-47e2-82f6-9fcdd09cf09e,Neighbors,J. Cole,0utlOiJy2weVl9WTkcEWHy,QMJMT1601088,False,0,[],2016-12-09,216520,...,0.898,0.283,0.000383,6.0,0.1100,-12.335,0.0,0.3560,138.970,0.469
9,0d32af4f-5493-4f3b-a2ad-f61fa55698e6,Change,J. Cole,3pjUyVbFmM96tYhSaKJwTt,QMJMT1601086,False,0,[],2016-12-09,331480,...,0.740,0.523,0.001420,11.0,0.0968,-10.753,0.0,0.2330,97.063,0.235